version: '3.8'

services:

  php:
    build: ./php
    volumes:
      - './App:/var/www/html'
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.9
    environment:
      MYSQL_ROOT_PASSWORD: your_password
    volumes:
      - mysqldata:/var/lib/mysql

  nginx:
    image: nginx:latest
    ports:
      - 8000:80
    links:
      - 'php'
    volumes:
      - './App:/var/www/html'
      - './nginx-conf:/etc/nginx/conf.d'
    depends_on:
      - php


volumes:

  mysqldata: